### ISSUE TITLE
[FEAT] 12 hour time format

### ISSUE THREAD

**Issue by leestarb** [meth1337/rice-clock#2]
Add 12 hours PM & AM

**Comment by meth1337** [comment]
Gonna add it in the next update! thx for idea <3

**Comment by meth1337** [comment]
> Add 12 hours PM & AM

By the way, you can replace `datetime.now().strftime("%H:%M:%S` on `datetime.today().strftime("%I:%M:%S %p")` in clock.py.
But I'll make this as an option anyway
