### ISSUE TITLE
[FEAT] Change time format with argument

### ISSUE THREAD

**Issue by leestarb** [meth1337/rice-clock#5]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when
Changing the time format requires running from source or using different binary

**Describe the solution you'd like**
Add `-12h` argument that changes the time format

**Describe alternatives you've considered**

**Additional context**

**Comment by meth1337** [comment]
are you switching between normal and 12h time format?

**Comment by leestarb** [comment]
> are you switching between normal and 12h time format?

No, but thats not cosy
